[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "itwinai-xtclim-plugin"
version = "0.1.0"
description = "xtclim plugin for itwinai"
authors = [{ name = "Christian Page", email = "christian.page@cerfacs.fr" }]
dependencies = ["itwinai"]

[tool.setuptools.packages.find]
# Declare this package as part of the `itwinai.plugins` namespace
where = ["src"]
include = ["itwinai.plugins.xtclim"]
